<MyGrid>
    sidebar: sidebar
    sidebar_label: sidebar_label
    canvas.before:
        Color:
            rgba: 0.9, 0.9 , 0.9, 0.3
        Rectangle:
            pos: self.pos
            size: self.size

    FloatLayout:
        size: root.width, root.height
        orientation: 'horizontal'

        # Sidebar
        FloatLayout:
            id: sidebar
            size_hint_x: 0.2
            orientation: 'vertical'
            canvas.before:
                Color:
                    rgba: 0.5, 0.5, 0.5, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                id: sidebar_label
                text: "prvky sa zobrazujú tu"
                color: 1, 1, 1, 1  # White text


        GridLayout:
            cols: 3
            id: chem_input
            Label:
                font_name: "comic"
                font_size: 30
                size_hint_x: 0.67
                text: "ChemioBiologio"
                size_hint_y: None
                height: 150
            Image:
                source: "logo_sgcr.png"
                size_hint_y: None
                size_hint_x: 0.1
                height: 150




<PopupOkno>:
    cols: 1
    GridLayout:
        id: riadok_smiles
        cols: root.pocet_koloniek
        size_hint: 0.8, 0.6
        pos_hint: {"x": 0.1, "y": 0.8}

    GridLayout:
        id: riadok_popisok
        cols: root.pocet_koloniek_desc
        size_hint: 0.9, 0.4
